include ../../../Makefile.in
include ../../../A2D_SHELLS.mk

CXX_OBJS = TACSDirector.h \
		   TACSShellElement.h \
		   TACSShellElementDefs.h \
		   TACSShellElementModel.h \
		   TACSShellElementQuadBasis.h \
		   TACSShellElementTransform.h \
		   TACSShellUtilities.h
		
default: ${CXX_OBJS}

clean:
	rm -f *.o
	rm -f **/*.o
	rm -f **/**/*.o