include ../../Makefile.in
include ../../A2D_SHELLS.mk

CXX_OBJS = TACSElementBasis.o \
         TACSElement.o \
		 TACSElementTypes.o
		
default: ${CXX_OBJS}

clean:
	rm -f *.o
	rm -f **/*.o
	rm -f **/**/*.o